use std::fmt::Write as _;
use std::path::Path;

fn main() {
    embed_templates();

    // Vite's bundle is EMBEDDED into the binary at compile time (that is what
    // `tauri::generate_context!` does with tauri.conf.json's `frontendDist`),
    // and `tauri-build` only emits rerun-if-changed for tauri.conf.json and
    // capabilities/.
    //
    // Without this, building one edition and then the other can leave the new
    // binary with the OLD bundle inside: cargo says "Finished" without
    // recompiling anything because no .rs changed. It is exactly the trap the
    // Simulation Studio's build.rs documents, and here it bites when packaging
    // the release, which builds full and tools back to back.
    watch(Path::new("../dist"));

    tauri_build::build()
}

/// Writes `$OUT_DIR/templates.rs`: the project and feature templates, as
/// tables of (relative path, bytes) that `include_bytes!` folds into the binary.
///
/// The wizard used to `git clone` both from GitHub and delete the .git right
/// after, which made the template a runtime dependency on the network, on the
/// `git` binary, and on a repository that could change under an already
/// installed app. It is about 220 KB; carrying it is cheaper than any of that.
///
/// Enumerated rather than globbed on purpose: a template is a coordinated set
/// of files -- feature_gen.rs rewrites MarsFeature.json, build.gradle,
/// settings.gradle and the java package tree together -- so the build should
/// fail loudly if one of them stops being there, not ship a template missing a
/// piece. Hidden files are INCLUDED: .gitignore, .wpilib/ and .vscode/ are not
/// incidental, they are most of what makes the folder a WPILib project.
fn embed_templates() {
    // Absolute, because `include_bytes!` resolves relative to the file doing
    // the including -- and that file is the generated one, which lives in
    // OUT_DIR, nowhere near the templates.
    let manifest = std::path::PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let repo = manifest
        .parent()
        .and_then(Path::parent)
        .expect("src-tauri hangs off desktop/, and desktop/ off the repo root");

    let mut out = String::from("// Generated by build.rs. Do not edit.
");
    for (name, dir) in [("PROJECT", "templates/project"), ("FEATURE", "templates/feature")] {
        let root = repo.join(dir);
        let root = root.as_path();
        let mut files = Vec::new();
        collect(root, root, &mut files);
        assert!(!files.is_empty(), "{} has no files; is the template missing?", root.display());
        files.sort();

        let _ = writeln!(out, "pub static {name}: &[(&str, &[u8])] = &[");
        for rel in &files {
            // Forward slashes in the key so the extractor builds the same paths
            // on every platform; rustc accepts them in include_bytes! on Windows
            // too.
            let abs = root.join(rel).display().to_string().replace('\\', "/");
            let _ = writeln!(out, "    ({rel:?}, include_bytes!({abs:?})),");
        }
        let _ = writeln!(out, "];");

        println!("cargo:rerun-if-changed={}", root.display());
    }

    let dest = Path::new(&std::env::var("OUT_DIR").unwrap()).join("templates.rs");
    std::fs::write(dest, out).expect("could not write templates.rs");
}

/// Every file under `dir`, as paths relative to `base`, with `/` separators.
fn collect(base: &Path, dir: &Path, files: &mut Vec<String>) {
    let entries = std::fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("could not read {}: {e}", dir.display()));
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            // A template is never checked out with a .git -- the subtree has
            // none -- but a developer poking at one by hand could leave one.
            if path.file_name().is_some_and(|n| n == ".git") {
                continue;
            }
            collect(base, &path, files);
        } else {
            let rel = path.strip_prefix(base).unwrap().display().to_string();
            files.push(rel.replace('\\', "/"));
        }
        println!("cargo:rerun-if-changed={}", path.display());
    }
}

fn watch(dir: &Path) {
    println!("cargo:rerun-if-changed={}", dir.display());
    let Ok(entries) = std::fs::read_dir(dir) else {
        // A clean checkout has no dist/ yet: the beforeBuildCommand's
        // `npm run build` creates it, and that creation already triggers the
        // rebuild through the line above.
        return;
    };
    for e in entries.flatten() {
        let p = e.path();
        if p.is_dir() {
            watch(&p);
        } else {
            println!("cargo:rerun-if-changed={}", p.display());
        }
    }
}
